package com.example.demo.entity;

import java.util.Date;
import java.util.List;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "companyMaster")
@Component
public class CompanyMaster1 {

	@DynamoDBHashKey(attributeName = "companyMasterId")
	@DynamoDBAutoGeneratedKey
	private String companyMasterId;
	@DynamoDBAttribute
	private String companyName;
	@DynamoDBAttribute
	private String companyAddress;
	@DynamoDBAttribute
	private String phoneno;
	@DynamoDBAttribute
	private String emailid;
	public CompanyMaster1() {
		super();
		// TODO Auto-generated constructor stub
	}
	public String getCompanyMasterId() {
		return companyMasterId;
	}
	public void setCompanyMasterId(String companyMasterId) {
		this.companyMasterId = companyMasterId;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getCompanyAddress() {
		return companyAddress;
	}
	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}
	public String getPhoneno() {
		return phoneno;
	}
	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}
	public String getEmailid() {
		return emailid;
	}
	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}
	
	
	
	
}